accounts/urls.py
from django.urls import path
from accounts import views


app_name= 'accounts'
urlpatterns = [
  
    path('dashboard/', views.dashboard ,name='dashboard'),
    path('demandeform/', views.Demande_form.as_view() ,name='demande_form'),
    

]

essikarea/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'pages.views.view_404'
handler500 = 'pages.views.view_500'
handler403 = 'pages.views.view_403'

urlpatterns = [
    path('',include('pages.urls')),
    path('listings/',include('listings.urls', namespace='listings')),
    path('accounts/',include('allauth.urls')),
    path('accounts/dash/',include('accounts.urls', namespace='accounts')),
    path('contacts/',include('contacts.urls')),
    path('realtors/',include('realtors.urls', namespace='realtors')),
    path('admin/', admin.site.urls),
]  

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views

app_name= 'listings'
urlpatterns = [
    path('', views.index ,name='listings'),  # /listings
    path('<int:listing_id>', views.listing ,name='listing'),  # listings/120
    path('search/',views.search,name='search'),    #listings/search
    path('add_steps/',views.Add_steps.as_view(),name='add_steps'), 
    path('add_property/',views.add_property,name='add_property'),    #/add_property
    path('<int:listing_id>/delete_property/',views.delete_property,name='delete_property'),    #/delete_property
    path('ajax/load-arrondissements/',views.load_arrondissements, name='ajax_load_arrondissements'), # AJAX
    path('ajax/load-districts/',views.load_districts, name='ajax_load_districts'), # AJAX
    
]

pages/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index ,name='index'),
    path('about/', views.about ,name='about'),
]

realtors/urls.py
from django.urls import path
from . import views

app_name = 'realtors'
urlpatterns = [
    path('', views.realtors,name='realtors'),  # /realtors
    path('<int:realtor_id>/', views.realtor_detail,name='realtors_detail'),  # /realtors/realtor_id
    path('realtor_search/', views.realtor_search,name='realtor_search'),  # /realtor_search
    path('demande/', views.Demande, name='demande'),
    path('profile/', views.Profile, name='profile'),
    path('show_div/', views.show_div, name='show_div'),
    

  

]

    

templates/partials/_alert.html
{% if messages %}
<ul class="messages" style="padding: 0px;" >
    {% for message in messages %}

    <div 
    {% if message.tags %} 
    id="meesage"
    class=" alert  alert-{{ message.tags }} alert-dismissible"
    {% endif %} 
    role="alert" 
    style="text-align: center;"
    >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{message}}
      </div>


    {% endfor %}
</ul>
{% endif %}

templates/partials/_footer.html
  <!-- Footer -->
  <footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> Essikarea Service immobilier
  </footer>

templates/partials/_navbar.html
<!-- Navbar -->
{% load static  %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'img/essika.png'  %}" class="logo" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li 
          {% if '/' == request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{% url 'index' %}">Acceuil</a>
          </li>
          <li 
          
          {% if 'about' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          
          >
            <a class="nav-link" href="{% url 'about' %}" >Qui sommes nous</a>
          </li>
          <li 
          
          {% if 'listings' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          
          >
            <a class="nav-link" href=" {% url 'listings:listings' %}  ">Propriétés</a>
          </li>

        
          <li 
          
          {% if 'add_property' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          
          >
          
    <a class="nav-link" href=" {% url 'listings:add_property' %}  ">Ajouter une propriété</a>
     
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">

          {% if request.user.is_authenticated %}

          <li class="nav-item dropdown"
          {% if 'dashboard' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          >
            <a  class="nav-link dropdown-toggle" href="#"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {{user.username}}</a>
               <div class="dropdown-menu" aria-labelledby="dropdown-a">
                <a class="dropdown-item" href="{%  url 'accounts:dashboard' %}">Dashboard</a>
                <a class="dropdown-item" href="{% url 'realtors:profile' %}">Profile</a>
                </div>
          </li>

          <li class="nav-item mr-3">
            <a class="nav-link" href="javascript:{ document.getElementById('logout').submit() }">
              <i class="fas fa-sign-in-alt"></i> Log Out</a>

              <form action="{% url 'account_logout'  %}" id="logout" method="POST" > 
                {% csrf_token  %}
                <input type="hidden">
              </form>

          </li>


          {% else  %}

          <li 
          {% if 'register' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{%  url 'account_signup'    %}">
              <i class="fas fa-user-plus"></i> Register</a>
          </li>
          <li 
          {% if 'login' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          
          >
            <a class="nav-link" href="{% url 'account_login'  %}">
              <i class="fas fa-sign-in-alt"></i>

              Login</a>
          </li>
          {% endif  %}
        </ul>
      </div>
    </div>
  </nav>

templates/partials/_topbar.html
  <!-- Top Bar -->
  <section id="top-bar" class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <i class="fas fa-phone"></i> +227 88 23 47 76
        </div>
        <div class="col-md-4">
          <i class="fas fa-envelope-open"></i> yvindjhonnelmahoukou@gmail.com
        </div>
        <div class="col-md-4">
          <div class="social text-right">
            <a href="#">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
              <i class="fab fa-facebook"></i>
            </a>
            <a href="#">
              <i class="fab fa-linkedin"></i>
            </a>
            <a href="#">
              <i class="fab fa-instagram"></i>
            </a>
            <a href="#">
              <i class="fab fa-pinterest"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>