essikarea/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'pages.views.view_404'
handler500 = 'pages.views.view_500'
handler403 = 'pages.views.view_403'

urlpatterns = [
    path('',include('pages.urls')),
    path('listings/',include('listings.urls', namespace='listings')),
    path('accounts/',include('allauth.urls')),
    path('accounts/dash/',include('accounts.urls', namespace='accounts')),
    path('contacts/',include('contacts.urls')),
    path('realtors/',include('realtors.urls', namespace='realtors')),
    path('admin/', admin.site.urls),
]  

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views

app_name= 'listings'
urlpatterns = [
    path('', views.index ,name='listings'),  # /listings
    path('<int:listing_id>', views.listing ,name='listing'),  # listings/120
    path('search/',views.search,name='search'),    #listings/search
    path('add_steps/',views.Add_steps.as_view(),name='add_steps'), 
    path('add_property/',views.add_property,name='add_property'),    #/add_property
    path('<int:listing_id>/delete_property/',views.delete_property,name='delete_property'),    #/delete_property
    path('ajax/load-arrondissements/',views.load_arrondissements, name='ajax_load_arrondissements'), # AJAX
    path('ajax/load-districts/',views.load_districts, name='ajax_load_districts'), # AJAX
    
]

pages/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index ,name='index'),
    path('about/', views.about ,name='about'),
]

realtors/urls.py
from django.urls import path
from . import views

app_name = 'realtors'
urlpatterns = [
    path('', views.realtors,name='realtors'),  # /realtors
    path('<int:realtor_id>/', views.realtor_detail,name='realtors_detail'),  # /realtors/realtor_id
    path('realtor_search/', views.realtor_search,name='realtor_search'),  # /realtor_search
    path('demande/', views.Demande, name='demande'),
    path('profile/', views.Profile, name='profile'),
    path('show_div/', views.show_div, name='show_div'),
    

  

]

    

templates/pages/about.html
{% extends 'base.html'  %}
{% block title %} | About Us {% endblock %}  
{% load static  %}

{% block content  %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">A propos de EssikaRea</h1>
          <p class="lead">Schooli est une plateforme de gestion de bien immobilier basé principalement au Congo brazzaville.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'index'  %}">
              <i class="fas fa-home"></i> Acceuil</a>
          </li>
          <li class="breadcrumb-item active"> About</li>
        </ol>
      </nav>
    </div>
  </section>

  <section id="about" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h2>Nous mettons à votre disposition des biens immobiliers qui repondent à vos goûts.</h2>
          <p class="lead">En un clic, trouvez la maison de vos rêve. cela vous évite des déplacements inutiles.</p>
          <img src="{% static 'img/about.jpg'  %}" alt="">
          <p class="mt-4">EssikaRea est l'outil idéal pour vos besoins en immobilier en république du Congo, Cette plateforme met en relation des propriétaires de biens immobiliers
            et des clients en quête de bels appartements au Congo Brazzaville.</p>
        </div>
        <div class="col-md-4">


           

          {%  for realtor in realtors  %}
          {% if realtor.profile.is_mvp %}

          <div class="card">
            {% if realtor.profile.photo %}
            <img class="card-img-top" src="{{  realtor.profile.photo.url }}" alt="Seller of the month">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">L'agent du mois</h5>
              <h6 class="text-secondary">{{realtor.name}}</h6>
              <p class="card-text">{{realtor.profile.description }}
              </p>
            </div>
          </div>

          {% else %}


          {% endif  %}
          {% endfor %}

        </div>
      </div>
    </div>
  </section>

  <!-- Work -->
  <section id="work" class="bg-dark text-white text-center">
    <h2 class="display-4">Nous travaillons pour vous.</h2>
    <h4>Faites nous parvenir la fiche complète de votre bien immobilier ou mettez le vous même en ligne gratuitement sur notre plateforme!</h4>
    <hr>
    <a href="{% url 'listings:listings' %}" class="btn btn-secondary text-white btn-lg">Voici nous propriétés ajoutées</a>
  </section>

  <!-- Team -->
  <section id="team" class="py-5">
    <div class="container">
      <h2 class="text-center">Notre équipe</h2>
      <div class="row text-center">

       
        {% if realtors %}
        {%  for realtor in realtors  %}
       
        <div class="col-md-4" >
          {% if realtor.profile.photo %}
          <img src="{{realtor.profile.photo.url}}" alt="" class="rounded-circle mb-3">
          {% endif %}
          {% if realtor.profile %}
          <h4 ><a href="{% url 'realtors:realtors_detail' realtor.id  %}">{{realtor.profile.user }}</a></h4>
          {%endif%}
          <h4>{{realtor.name }}</h4>
          <p class="text-success">
            
            {% if realtor.is_mvp  %}
            <i class="fas fa-award text-success mb-3"></i>

            {% endif %}
            
            Agent</p>
          <hr>
          <p>
            <i class="fas fa-phone"></i> {{realtor.phone_number}}  </p>
          <p>
            <i class="fas fa-envelope-open"></i> {{realtor.email}}</p>
            
        </div>

        


        {% endfor  %}



        {% else  %}
        <div class="col-md-12">
          <p>Aucun Agent disponible</p>
        </div>


        {% endif  %}
      </div>
      {% if  request.user.is_authenticated == False %}
      
      <div class="col-md-6 col-lg-4 mb-4 text-right">
        
        <h2>
          <a href="{% url 'realtors:profile'  %} "><button class="btn btn-primary ">Devenir Agent immobilier</button></a>
        </h2>
      
      </div>
    
      {%endif %}
    </div>
  </section>


{% endblock %}

templates/pages/index.html
{% extends 'base.html'  %}
{% load humanize  %}
{% block title %} | Bienvenu {% endblock %}  
{% load static %}

{% block content  %}

<!-- Showcase -->

<section id="showcase" style="background: url('/static/img/showcase2.jpeg') no-repeat top center fixed;">
    <div class="container text-center">
      
      <div class="home-search p-5">
        <div class="overlay p-5">
          <h1 class="display-4 mb-4">
            Chercher votre bien immobilier
          </h1>
          <p class="lead">Vous y trouverez la rapidement la maison qui vous correspond</p>
          <div class="search">
            {% include 'listings/searchform.html' %}
          </div>
        </div>
        
      </div>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-5">
    <div class="container">
      <h3 class="text-center mb-3">Derniers Ajouts</h3>
      <div class="row">

        {% if listings %}

        {% for listing in listings  %}

        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            {% if listing.photo_main %}
          <img class="card-img-top" src="{{listing.photo_main.url}}" alt="" width=200px height = 200px >
            {% endif %}
            <div class="card-img-overlay">
              <h2>
                <span class="badge badge-secondary text-white">{{listing.price | intcomma}} FCFA</span>
              </h2>
            </div>
            <div class="card-body">
              <div class="listing-heading text-center">
                <h4 class="text-primary">{{listing.title}}</h4>
                <p>
                  <i class="fas fa-map-marker text-secondary"></i> {{listing.ville}} {{listing.arrondissement}}, {{listing.district}}</p>
              </div>
              <hr>
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-car"></i> {{ listing.type_immo }}</div>
                  {% if listing.sqft  %}
                  <div class="col-6">
                    <i class="fas fa-th-large"></i> surface: {{ listing.sqft }} m²
                   </div>
                   {% endif %}
                  
                  {% if listing.lot_size  %}
                  <div class="col-6">
                    <i class="fas fa-th-large"></i> Taille de la parcelle: {{ listing.lot_size }} m²
                   </div>
                   {% endif %}
               
              </div>
              <hr>
              <div class="row py-2 text-secondary">
                <div class="col-12">
                  <i class="fas fa-user"></i> {{ listing.address }}</div>
                  <div class="col-12">
                    <i class="fas fa-user"></i> {{ listing.description|truncatewords:50 }}</div>
                </div>
              
              <hr>
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-user"></i> {{listing.realtor}}</div>
              </div>
              <div class="row text-secondary pb-2">
                <div class="col-12">
                  <i class="fas fa-clock"></i> {{listing.list_date | timesince}}</div>
              </div>
              <hr>
              <a href=" {% url 'listings:listing' listing.id  %}  " class="btn btn-primary btn-block">Plus d'info</a>
            </div>
          </div>
        </div>


        {% endfor %}

        {% else  %}
        <div class="col-md-12">
          <p>Aucun ajout disponible.</p>
        </div>

        {% endif %}

        
      </div>
    </div>
  </section>

  <section id="services" class="py-5 bg-primary text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-4">
          <i class="fas fa-comment fa-4x mr-4"></i>
          <hr>
          <h3>Services de consultation</h3>
          <p>Vous pouvez nous contactez à nos numéros ou nous envoyer un e-mail pour des questions rélatives à la gestion des propriétés.</p>
        </div>
        <div class="col-md-4">
          <i class="fas fa-home fa-4x mr-4"></i>
          <hr>
          <h3>Gestion de Propriété</h3>
          <p>Nos propriétés sont ajoutés par des volantaires quelconques après s'etre inscris sur le site. en s'inscrivant en tant qu'agent
            vous avez la possibilité de bien gerer vos biens immobiliers gratuitement.</p>
        </div>
        <div class="col-md-4">
          <i class="fas fa-suitcase fa-4x mr-4"></i>
          <hr>
          <h3>Location et vente</h3>
          <p>Nos mettons sur notre site des annonces relatives à la location et la vente des bien immobiliers à travers tout le Congo, 
            pour toutes informations supplementaires, veuillez contacter l'agent immobilier responsable de l'annonce..</p>
        </div>
      </div>
    </div>
  </section>

  <script src="{% static 'js/jquery-3.5.1.min.js'  %}"></script>
  <script src="{% static 'myjs/jqueryComm.js' %}"></script>
  <script src="{% static 'myjs/jqueryVille.js' %}"></script>
  <script src="{% static 'myjs/jqueryGenre.js' %}"></script>
  <script src="{% static 'myjs/jqueryType.js' %}"></script>

{% endblock %}