accounts/urls.py
from django.urls import path
from accounts import views


app_name= 'accounts'
urlpatterns = [
  
    path('dashboard/', views.dashboard ,name='dashboard'),
    path('demandeform/', views.Demande_form.as_view() ,name='demande_form'),
    

]

essikarea/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'pages.views.view_404'
handler500 = 'pages.views.view_500'
handler403 = 'pages.views.view_403'

urlpatterns = [
    path('',include('pages.urls')),
    path('listings/',include('listings.urls', namespace='listings')),
    path('accounts/',include('allauth.urls')),
    path('accounts/dash/',include('accounts.urls', namespace='accounts')),
    path('contacts/',include('contacts.urls')),
    path('realtors/',include('realtors.urls', namespace='realtors')),
    path('admin/', admin.site.urls),
]  

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views

app_name= 'listings'
urlpatterns = [
    path('', views.index ,name='listings'),  # /listings
    path('<int:listing_id>', views.listing ,name='listing'),  # listings/120
    path('search/',views.search,name='search'),    #listings/search
    path('add_steps/',views.Add_steps.as_view(),name='add_steps'), 
    path('add_property/',views.add_property,name='add_property'),    #/add_property
    path('<int:listing_id>/delete_property/',views.delete_property,name='delete_property'),    #/delete_property
    path('ajax/load-arrondissements/',views.load_arrondissements, name='ajax_load_arrondissements'), # AJAX
    path('ajax/load-districts/',views.load_districts, name='ajax_load_districts'), # AJAX
    
]

pages/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index ,name='index'),
    path('about/', views.about ,name='about'),
]

realtors/urls.py
from django.urls import path
from . import views

app_name = 'realtors'
urlpatterns = [
    path('', views.realtors,name='realtors'),  # /realtors
    path('<int:realtor_id>/', views.realtor_detail,name='realtors_detail'),  # /realtors/realtor_id
    path('realtor_search/', views.realtor_search,name='realtor_search'),  # /realtor_search
    path('demande/', views.Demande, name='demande'),
    path('profile/', views.Profile, name='profile'),
    path('show_div/', views.show_div, name='show_div'),
    

  

]

    

listings/models.py
from django.db import models
from realtors.models import Profile
from datetime import datetime
from PIL import Image


class Ville(models.Model):
    name = models.CharField(max_length=255,blank=True,null=True)
    def __str__(self):
        return self.name
    

class Arrondissement(models.Model):
    name = models.CharField(max_length=255,blank=True,null=True)
    ville = models.ForeignKey(Ville, on_delete=models.CASCADE,blank=True,null=True)

    def __str__(self):
        return self.name
class District(models.Model):
    name = models.CharField(max_length=255,blank=True,null=True)
    arrondissement = models.ForeignKey(Arrondissement, on_delete=models.CASCADE,blank=True,null=True)

    def __str__(self):
        return self.name

class Propriete(models.Model):
    realtor=models.ForeignKey(Profile,on_delete=models.DO_NOTHING)
    title=models.CharField(max_length=200)
    address=models.CharField(max_length=200)
    ville=models.CharField(max_length=200,null = True,blank=True)
    arrondissement=models.CharField(max_length=200,null = True,blank=True)
    district=models.CharField(max_length=200,null = True,blank=True)
    type_immo = models.CharField(max_length=200,null = True,blank=True)
    gender = models.CharField(max_length=200,null=True,blank=True)
    price=models.IntegerField()
    description=models.TextField()
    list_date=models.DateTimeField(default=datetime.now,blank=True)
    photo_main=models.ImageField(upload_to='photos/%Y/%m/%d/',default='default.png')
    photo_1=models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True,null=True)
    photo_2=models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True,null=True)
    photo_3=models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True,null=True)
    photo_4=models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True,null=True)
    photo_5=models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True,null=True)
    photo_6=models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True,null=True)
    is_published=models.BooleanField(default=True)
    bedroom=models.IntegerField(blank=True,null=True)
    room = models.IntegerField(blank=True,null=True)
    bathroom=models.IntegerField(blank=True,null=True)
    garage=models.IntegerField(blank=True,null=True)
    kitchen = models.IntegerField( blank=True,null=True)
    veranda = models.IntegerField(blank=True,null=True)
    sqft=models.IntegerField(blank=True,null=True)
    lot_size=models.DecimalField(max_digits=5,decimal_places=1,blank=True,null=True)


    def __str__(self):
        return self.title





    

   

listings/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Propriete



class AddProperty(forms.ModelForm):
    class Meta:
        model = Propriete
        exclude = ['realtor','is_published']
        widgets = {
            
            'title': forms.TextInput(attrs={'class':'form-control '}),
            'address':forms.TextInput(attrs={'class':'form-control'}),
            'ville':forms.TextInput(attrs={'class':'form-control'}),
            'district': forms.TextInput(attrs={'class':'form-control'}),
            'arrondissement': forms.TextInput(attrs={'class':'form-control'}),
            'description': forms.Textarea(attrs={'class':'form-control'}),
            'price': forms.NumberInput(attrs={'class':'form-control'}),
            'bedroom': forms.NumberInput(attrs={'class':'form-control'}),
            'bathroom': forms.NumberInput(attrs={'class':'form-control'}),
            'garage': forms.NumberInput(attrs={'class':'form-control'}),
            'list_date': forms.DateInput(attrs={'class':'form-control'}),
            'sqft': forms.NumberInput(attrs={'class':'form-control'}),
            'lot_size': forms.NumberInput(attrs={'class':'form-control'}),
            'photo_main': forms.FileInput(attrs={'class':'form-control'}),
            'photo_1': forms.FileInput(attrs={'class':'form-control'}),
            'photo_2': forms.FileInput(attrs={'class':'form-control'}),
            'photo_3': forms.FileInput(attrs={'class':'form-control'}),
            'photo_4': forms.FileInput(attrs={'class':'form-control'}),
            'photo_5': forms.FileInput(attrs={'class':'form-control'}),
            'photo_6': forms.FileInput(attrs={'class':'form-control'}),
            
        }
            
    

   
    
   
               

listings/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Propriete,Ville,Arrondissement,District
from realtors.models import Profile,Demande
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from .choices import bedroom_choices,price_choices,ville_choices,arrondissement_choices,type_immo,gender_choices,price_choices_sell
from .forms import AddProperty
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView,UpdateView,TemplateView
from django.http import JsonResponse
# Create your views here.

def index(request):
    listings=Propriete.objects.filter(is_published=True).order_by('-list_date')
    villes = Ville.objects.all()
    paginator=Paginator(listings,6)
    page=request.GET.get('page')
    
    try:
        paged_listing = paginator.page(page)
    except PageNotAnInteger:
        paged_listing = paginator.page(1)
    except EmptyPage:
        paged_listing = paginator.page(paginator.num_pages)
    context = {
        'listings' :  paged_listing,
        'paginate': True,
        'villes':villes,
        'bedroom_choices':bedroom_choices,
        'price_choices':price_choices,
        'price_choices_sell':price_choices_sell,
        'ville_choices':ville_choices,
        'arrondissement_choices':arrondissement_choices,
        'gender_choices':gender_choices,
        'type_immo':type_immo,
    }
    return render(request,'listings/listings.html',context)

def listing(request,listing_id):

    listing=get_object_or_404(Propriete,pk=listing_id)
    dem=listing.realtor.demande_set.all()

    context={
        'listing':listing,
        'dem':dem
    }

    return render(request,'listings/listing.html',context)

def search(request):

    query_list=Propriete.objects.order_by('-list_date')
    villes=Ville.objects.all()

    # KeyWords

    if 'keywords' in request.GET:
        keywords=request.GET['keywords']

        if keywords:
            query_list=query_list.filter(description__icontains=keywords)


    if 'ville' in request.GET:
        ville=request.GET['ville']

        if ville:
            ville = Ville.objects.get(id=ville).name
            query_list=query_list.filter(ville__iexact=ville)
            
            
    
    if 'arrondissement' in request.GET:
       
        arrondissement=request.GET['arrondissement']

        if arrondissement:
            arrondissement = Arrondissement.objects.get(id=arrondissement).name
            query_list=query_list.filter(arrondissement__iexact=arrondissement)
    
    if 'district' in request.GET:
        district=request.GET['district']

        if district:
            district = District.objects.get(id=district).name
            query_list=query_list.filter(district__iexact=district)

    if 'bedrooms' in request.GET:
        bedroom=request.GET['bedrooms']

        if bedroom:
            query_list=query_list.filter(bedroom__lte=bedroom)
    
    if 'kitchen' in request.GET:
        kitchen=request.GET['kitchen']

        if kitchen:
            query_list=query_list.filter(kitchen__lte=kitchen)

    if 'rooms' in request.GET:
        room=request.GET['rooms']

        if room:
            query_list=query_list.filter(room__lte=room)
    
    if 'price' in request.GET:
        price=request.GET['price']

        if price:
            query_list=query_list.filter(price__lte=price)

    if 'sell_price' in request.GET:
        sell_price=request.GET['sell_price']

        if sell_price:
            query_list=query_list.filter(price__lte=sell_price)

    if 'type' in request.GET:
        type_l=request.GET['type']

        if type_l :
            query_list=query_list.filter(type_immo__iexact=type_l)
    
    if 'genre' in request.GET:
        genre=request.GET['genre']

        if genre :
            query_list=query_list.filter(gender__iexact=genre)

    if 'veranda' in request.GET:
        veranda=request.GET['veranda']

        if veranda :
            query_list=query_list.filter(veranda__iexact=veranda)
    
    context={
        'listings':query_list,
        'villes':villes,
        'bedroom_choices':bedroom_choices,
        'price_choices':price_choices,
        'price_choices_sell':price_choices_sell,
        'ville_choices':ville_choices,
        'arrondissement_choices':arrondissement_choices,
        'gender_choices':gender_choices,
        'type_immo':type_immo,
        'values':request.GET
    }
    return render(request,'listings/search.html',context)


@login_required
def add_property(request):
    
    if request.method == 'POST':
        title = request.POST.get('title')
        address = request.POST.get('address')
        ville = request.POST.get('ville')
        arrondissement = request.POST.get('arrondissement')
        district = request.POST.get('district')
        description = request.POST.get('description')
        price = request.POST.get('price')
        bedrooms = request.POST.get('bedrooms')
        bathrooms = request.POST.get('bathrooms')
        garage = request.POST.get('garage')
        rooms = request.POST.get('rooms')
        veranda = request.POST.get('veranda')
        genre = request.POST.get('genre')
        type_l= request.POST.get('type')
        sqft = request.POST.get('sqft')
        lot_size = request.POST.get('lot_size')
        photo_main = request.FILES.get('photo_main')
        photo_1 = request.FILES.get('photo_1')
        photo_2 = request.FILES.get('photo_2')
        photo_3 = request.FILES.get('photo_3')
        photo_4 = request.FILES.get('photo_4')
        photo_5 = request.FILES.get('photo_5')
        photo_6 = request.FILES.get('photo_6')
        
        
        realtor = request.user.profile
        demande=Demande.objects.filter(realtor=realtor)
        ville = Ville.objects.get(id = ville).name
        arrondissement = Arrondissement.objects.get(id = arrondissement).name
        district = District.objects.get(id = district).name
        type_l = type_immo[type_l]

        if genre =='MA':
            
            propriety = Propriete(title=title, address=address,room=rooms, veranda=veranda, ville =ville,arrondissement =arrondissement,realtor =realtor, district = district,description = description,price =price,bedroom =bedrooms,bathroom = bathrooms,garage = garage,sqft = sqft,gender = genre,type_immo = type_l, photo_main = photo_main,photo_1 =photo_1,photo_2 = photo_2,photo_3 = photo_3,photo_4 = photo_4,photo_5 = photo_5,photo_6 = photo_6)
            propriety.save()
            messages.success(request, 'good')
            return redirect('listings:listings')
    
        elif genre =='PA':
           propriety = Propriete(title=title, address=address, ville =ville,arrondissement =arrondissement,realtor =realtor, district = district,description = description,price =price,lot_size = lot_size, gender = genre,type_immo = type_l, photo_main = photo_main,photo_1 =photo_1,photo_2 = photo_2,photo_3 = photo_3,photo_4 = photo_4,photo_5 = photo_5,photo_6 = photo_6)
           propriety.save()
           messages.success(request, 'good')
           return redirect('listings:listings')
#else genre =='Studio':
        else:
            propriety = Propriete(title=title, address=address, ville =ville,arrondissement =arrondissement,realtor =realtor, district = district,description = description,price =price,gender = genre,type_immo = type_l, photo_main = photo_main,photo_1 =photo_1,photo_2 = photo_2,photo_3 = photo_3,photo_4 = photo_4,photo_5 = photo_5,photo_6 = photo_6)
            propriety.save()
            messages.success(request, 'good')
            return redirect('listings:listings')

        #elif genre =='Immeuble' or genre=='Appartement':
           # propriety = Lot(title=title, address=address,room=rooms,  ville =ville,arrondissement =arrondissement,realtor =realtor, district = district,description = description,price =price, gender = genre,type_immo = type_l, photo_main = photo_main,photo_1 =photo_1,photo_2 = photo_2,photo_3 = photo_3,photo_4 = photo_4,photo_5 = photo_5,photo_6 = photo_6)
            #propriety.save()
            #messages.success(request, 'good')
            #return redirect('listings:listings')

    else:
        villes =  Ville.objects.all()  
    context ={
        'villes':villes,
        'bedroom_choices':bedroom_choices,
        'ville_choices':ville_choices,
        'arrondissement_choices':arrondissement_choices,
        'gender_choices':gender_choices,
        'type_immo':type_immo,
    }

    return render(request, 'listings/add_property.html',context)

@login_required  
def delete_property(request,listing_id):
    Propriete(id= listing_id).delete()
    return redirect('listings:listings')


class Add_steps(TemplateView):
    template_name = 'listings/add_steps.html'


# AJAX
def load_arrondissements(request):
        title ='Arrondissement'
        ville_id = request.GET.get('ville')
        arrondissements = Arrondissement.objects.filter(ville_id=ville_id).order_by('name')
        return render(request, 'listings/arrondissement_dropdown_list_options.html', {'arrondissements': arrondissements,
        'title':title
        })

def load_districts(request):
        title ='District'
        arrondissement_id = request.GET.get('arrondissement')
        districts = District.objects.filter(arrondissement_id=arrondissement_id).order_by('name')
        return render(request, 'listings/arrondissement_dropdown_list_options.html', {'arrondissements': districts,
        'title':title 
        })

listings/templates/listings/add_property.html
{% extends 'base.html'  %}
{% load static %}

{% block title %} | Ajouter une propriété {% endblock %}  

{% load humanize %}
{% block content  %}


{% if request.user.is_authenticated %}
    {% if request.user.profile.is_mvp %}
    <p>{{request.user.username}}</p>
   
 <!-- <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
          <p>Bonjour!!!</p>
          <p>En ajoutant gratuitement une propriété sans votre compte agent, elle ne s'afficherait sur notre site que pendant une semaine.
          </p>
          <p>Veuillez créer un <a href="#">compte agent</a> pour que vous puissiez bien gerer vos propriétés!!!</p>
                 <a href="#"><button class="btn btn-secondary">Creer un compte Agent</button></a> 
              
              </div>
            </div>
          </div>  -->
      

<section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container">
      <div class="row text-center">

        <div class="col-md-12">
          <p>Veuillez remplir ce formulaire pour ajouter gratuitement votre propriété</p>



            <form action="{% url 'listings:add_property' %}" method="POST" enctype="multipart/form-data" data-arrondissements-url="{% url 'listings:ajax_load_arrondissements' %}" data-districts-url="{% url 'listings:ajax_load_districts' %}" id="searchForm">
                {% csrf_token %}
              <!-- Form Row 1 -->
              <div class="form-row">
         
                    <div class="col-md-4 mb-3">
                      <label class="sr-only">Titre*</label>
                      <input type="text" name="title" class="form-control" placeholder="Titre" 
                    
                      >
                    </div>
      

                    <div class="col-md-4 mb-3">
                      <label class="sr-only">Ville*</label>
                      <select name="ville" id="ville" class="form-control">
                        <option selected="true" disabled="disabled">Ville (Toutes)</option>
                        {% for ville in villes %}
                          {% if ville  %}
                          <option value="{{ ville.id }}">{{ville.name}}</option>
                          
                       
                          {% endif %}
              
              
                        {% endfor  %}
                      </select>
                    </div>
        
                    <div class="col-md-4 mb-3">
                      <label class="sr-only">Arrondissement</label>
                      <select name="arrondissement" id="arrondissement" class="form-control" >
                        
                      </select>
                    </div>
                  </div>
            
               <!-- Form Row 2 -->
               <div class="form-row">
                
                <div class="col-md-4 mb-3">
                  <label class="sr-only">Quartier</label>
                  <select name="district" id="district" class="form-control" >
                    
                  </select>
                </div>
                <div class="col-md-4 mb-3">
                  <label class="sr-only">Address</label>
                  <input type="text" name="address" class="form-control" placeholder="Address">
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">Type</label>
                  <select name="type" class="form-control" id="type">
                    <option selected="true" disabled="disabled">Type (Any)</option>
                    {% for key,value in type_immo.items %}
          
                      <option value="{{key}}">{{value}}</option>
          
          
                    {% endfor  %}
                  </select>
                </div>
                
              
            </div>
                    <!-- Form Row 3 -->
                    <div class="form-row">
                      <div class="col-md-4 mb-3">
                        <label class="sr-only">Genre</label>
                        <select name="genre" class="form-control" id="genre">
                          <option selected="true" disabled="disabled">Genre (Any)</option>
                          {% for key,value in gender_choices.items %}
                
                      
                            <option value="{{key}}" id="{{ value }}">{{value}}</option>
                          
                
                
                          {% endfor  %}
                        </select>
                      </div>

                      <div class="col-md-4 mb-3">
                        <label class="sr-only" >Bedrooms</label>
                        <select name="bedrooms" class="form-control" id="bedrooms" hidden='true'>
                          <option selected="true" disabled="disabled">Bedrooms (Any)</option>
                          {% for key,value in bedroom_choices.items %}
                
                            <option value="{{key}}">{{value}}</option>
                        
                
                
                          {% endfor  %}
                        </select>
                      </div>
                      <div class="col-md-4 mb-3">
                        <label class="sr-only">Kitchen</label>
                        <select name="kitchen" class="form-control" id="kitchen" hidden="true">
                          <option selected="true" disabled="disabled">Cuisine (Any)</option>
                          {% for key,value in bedroom_choices.items %}
              
                            <option value="{{key}}">{{value}}</option>
                           
              
              
                          {% endfor  %}
                        </select>
                      </div>
                    </div>

                       <!-- Form Row 4 -->
                     
                
                      <div class="form-row">
                        <div class="col-md-4 mb-3">
                          <label class="sr-only">Salon</label>
                          <input type="number"  name="rooms" id="rooms" class="form-control" placeholder="nombre de salon" hidden='true'>
                           
                        </div>
                       
                    

                      <div class="col-md-4 mb-3">
                        <label class="sr-only">Bathrooms</label>
                        <input type="number"  name="bathrooms" class="form-control" placeholder="Bathrooms" id="bathrooms" hidden='true'>
                      </div>
                      <div class="col-md-4 mb-3">
                        <label class="sr-only">Garage</label>  
                        <input type="number"  name="garage" id="garage" class="form-control" placeholder="Garage" hidden="true">
                         
                      </div>
                     
                      
                      
                    </div>

                     <!-- Form Row 5 -->
                     
                     <div class="form-row">
                      <div class="col-md-4 mb-3">
                        <label class="sr-only">Veranda</label>  
                        <input type="number"  name="veranda" id="veranda" class="form-control" placeholder="Veranda" hidden="true">
                         
                      </div>
                      <div class="col-md-4 mb-3">
                        <label class="sr-only">Price</label>  
                        <input type="number"  name="price" class="form-control" placeholder="Price">
                         
                      </div>
                        <div class="col-md-4 mb-3">
                            <label class="sr-only">Sqft</label>
                          <input type="number" name="sqft" id="sqft" class="form-control" placeholder="metres carrés" hidden='false'>
                        </div>
                        
                    </div>


                      <!-- Form Row 5 -->
                     <div class="form-row">
                      <div class="col-md-4 mb-3">
                        <label class="sr-only">Lot_size</label>
                      <input type="number" name="lot_size" id="lot_size" class="form-control" placeholder="Taille de la parcelle" hidden='true'>
                    </div>
                      
                    <div class="col-md-4 mb-3">
                      <label class="sr-only">Photo_main</label>
                    <input type="file" name="photo_main" class="form-control" placeholder="Photo_main">
                  </div>
                  
                     </div> 
                    
                       <!-- Form Row 7 -->
                     <div class="form-row">
                        <div class="col-md-4 mb-3">
                          <label class="sr-only">Photo_1</label>
                          <input type="file" name="photo_1"  class="form-control" placeholder="Photo_1">
                        </div>
                        <div class="col-md-4 mb-3">
                            <label class="sr-only">Photo_2</label>
                          <input type="file" name="photo_2"  class="form-control" placeholder="Photo_2">
                        </div>
                        <div class="col-md-4 mb-3">
                            <label class="sr-only">Photo_3</label>
                          <input type="file" name="photo_3"  class="form-control" placeholder="Photo_3">
                        </div>
                      </div>
      <!-- Form Row 8 -->
      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label class="sr-only">Photo_4</label>
          <input type="file" name="photo_4"  class="form-control" >
        </div>
        <div class="col-md-4 mb-3">
            <label class="sr-only">Photo_5</label>
          <input type="file" name="photo_5"  class="form-control">
        </div>
        <div class="col-md-4 mb-3">
            <label class="sr-only">Photo_6</label>
          <input type="file" name="photo_6" class="form-control">
        </div>
      </div>
                       <!-- Form Row 5 -->
                     <div class="form-row">
                        <div class="col-md-12">
                          
                          <textarea  name="description" class="form-control" placeholder="Description">Description</textarea>
                        </div>
                        
                         
                      </div>
                    <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
                  </form>
                </div>
              </div>
            </div>
          </section>


          {% else %}
       
        <section id="overviews" class="section wb">
            <div class="container">
                <div class="section-title row text-center">
                    <div class="col-md-12">
                        <h2 class="lead">Creer un compte agent pour ajouter un bien immobilier</h2>
                          <p>Creer un compte afin d'ajouter une annonce dans le site. Choisiser le format qui vous correspond. </p>
                        
                    </div>
                </div><!-- end title -->
        
                <hr class="invis"> 
        
                <div class="row"> 
                    <div class=" card col-lg-6 col-12">
                        <div class="card-body">
                            
    
                            <div class="card-title">
                                <h5><a href="#">Particulier(gratuit)</a></h5>
                                <h6 class="card-subtitle mb-2 text-muted">Pour les particuliers</h6>
                            
                                <p class="card-text">
                                Créer un compte d'agent gratuitement, en tant que particulier afin de poster votre bien immobilier. </p>
                                <a href="{% url 'accounts:demande_form' %}" class="card-link btn btn-primary">Creer</a>
                              
                            
                        </div>
                        </div>
                    </div><!-- end col -->
               
                    
                      <div class="card col-lg-6 col-12" >
                      <div class="card-body">
                        <div class="card-title">
                        <h5>Proffessionel(5000 FCFA)</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Pour les agents immobiliers</h6>
                        <p class="card-text">Créer un compte professionel pour votre agence, afin de poster votre bien immobilier. </p>
                        <a href="#" class="card-link btn btn-primary">Creer</a>
                        
                        </div> 
                      </div>
                  </div><!-- end col -->

                </div>
            </div>
        </section>

     
         <br>   <br>  <br> <br>   <br>  
         
{% endif %}
{% endif %}

<script src="{% static 'js/jquery-3.5.1.min.js'  %}"></script>
   <script src="{% static 'myjs/jqueryComm.js' %}"></script>
   <script src="{% static 'myjs/jqueryVille.js' %}"></script>
   <script src="{% static 'myjs/jqueryGenre.js' %}"></script>
   <script src="{% static 'myjs/jqueryType.js' %}"></script>
   <script src="{% static 'myjs/add_prop.js' %}"></script>
{% endblock %}

           
          
         

listings/templates/listings/add_steps.html
{% extends 'base.html'  %}

{% block title %} | Ajouter une propriété {% endblock %}  

{% load humanize %}
{% block content  %}
<section id="overviews" class="section wb">
    <div class="container">
        <div class="section-title row text-center">
            <div class="col-md-12" >
                <h2 class="lead">Creer un compte agent pour ajouter un bien immobilier</h2>
                  <p>Creer un compte afin d'ajouter une annonce dans le site. Choisiser le format qui vous correspond. </p>
                
            </div>
        </div><!-- end title -->

        <hr class="invis"> 

        <div class="row"> 
            <div class=" card  col-12">
                <div class="card-body">
                    
                  
                    <div class="card-title"><h2>Etapes pour ajouter un bien immobilier</h2>  
                        <p class="card-text">  
                            <ul> 
                            <li><a href="{% url 'realtors:profile' %}">Mettez d'abord à jour votre profile</a> </li>  
                    
                            <li><a href="{% url 'listings:add_property'%}">Choisissez un plan</a> </li>            
       
                        </ul> 
                      
                        </p>
                        <br>
                        <br>
                        <br>
                        <br>
                </div>
                </div>
            </div><!-- end col -->
       
            
              

        </div>
    </div>
    <br><br><br>
</section>





{% endblock %}