essikarea/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'pages.views.view_404'
handler500 = 'pages.views.view_500'
handler403 = 'pages.views.view_403'

urlpatterns = [
    path('',include('pages.urls')),
    path('listings/',include('listings.urls', namespace='listings')),
    path('accounts/',include('allauth.urls')),
    path('accounts/dash/',include('accounts.urls', namespace='accounts')),
    path('contacts/',include('contacts.urls')),
    path('realtors/',include('realtors.urls', namespace='realtors')),
    path('admin/', admin.site.urls),
]  

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views

app_name= 'listings'
urlpatterns = [
    path('', views.index ,name='listings'),  # /listings
    path('<int:listing_id>', views.listing ,name='listing'),  # listings/120
    path('search/',views.search,name='search'),    #listings/search
    path('add_steps/',views.Add_steps.as_view(),name='add_steps'), 
    path('add_property/',views.add_property,name='add_property'),    #/add_property
    path('<int:listing_id>/delete_property/',views.delete_property,name='delete_property'),    #/delete_property
    path('ajax/load-arrondissements/',views.load_arrondissements, name='ajax_load_arrondissements'), # AJAX
    path('ajax/load-districts/',views.load_districts, name='ajax_load_districts'), # AJAX
    
]

pages/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index ,name='index'),
    path('about/', views.about ,name='about'),
]

realtors/urls.py
from django.urls import path
from . import views

app_name = 'realtors'
urlpatterns = [
    path('', views.realtors,name='realtors'),  # /realtors
    path('<int:realtor_id>/', views.realtor_detail,name='realtors_detail'),  # /realtors/realtor_id
    path('realtor_search/', views.realtor_search,name='realtor_search'),  # /realtor_search
    path('demande/', views.Demande, name='demande'),
    path('profile/', views.Profile, name='profile'),
    path('show_div/', views.show_div, name='show_div'),
    

  

]

    

realtors/models.py
from django.db import models
from datetime import datetime
from PIL import Image
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    photo=models.ImageField(default='default.png', upload_to='photos/%Y/%m/%d/')
    description=models.CharField(max_length=255, blank=True, null=True)
    is_mvp=models.BooleanField(default=False)
    hire_date=models.DateTimeField(default=datetime.now,blank=True)
    website_url = models.CharField(max_length=255, blank=True, null=True)
    facebook_url = models.CharField(max_length=255, blank=True, null=True)
    instagram_url = models.CharField(max_length=255, blank=True, null=True)
    twitter_url = models.CharField(max_length=255, blank=True, null=True)
    linkedin_url = models.CharField(max_length=255, blank=True, null=True)
    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.photo.path)
        if img.height >100 or img.width>100:
            output_size = (100,100)
            img.thumbnail(output_size)
            img.save(self.photo.path)


class Demande(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    phone_number = models.CharField(max_length=15)


    def __str__(self):
        return self.profile.user.username

realtors/forms.py
from django import forms
from django.contrib.auth.models import User
from realtors.models import Profile

class userUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email']


class profileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields =['description','photo','website_url','facebook_url','twitter_url','linkedin_url','instagram_url']

realtors/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from realtors.forms import profileUpdateForm, userUpdateForm
from realtors.models import Profile as Pro
from realtors.models import  Demande as Dem
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.http import JsonResponse


# Create your views here.

def realtors(request):
    realtors=Pro.objects.all()
    paginator=Paginator(realtors,6)
    page=request.GET.get('page')
    paged_listing=paginator.get_page(page)
    context={
    'realtors' :  paged_listing
    
}
    return render(request,'realtors/realtors.html',context)

def realtor_detail(request,realtor_id):

    realtor =get_object_or_404(Pro,pk=realtor_id)

    context={
        'realtor':realtor
    }

    return render(request,'realtors/realtor_detail.html',context)

def realtor_search(request):

    query_list=Pro.objects.all()

    # KeyWords

    if 'keywords' in request.GET:
        keywords=request.GET['keywords']

        if keywords:
            query_list=query_list.filter(name__icontains=keywords)

    
    
    context={
        'realtor_search':query_list,
    }
    return render(request,'realtors/realtor_search.html',context)




@login_required
def Profile(request):
    
    if request.method == 'POST':
        u_form = userUpdateForm(request.POST,instance=request.user)
        p_form = profileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Votre compte a été mis à jour avec succès!')
            return redirect('listings:add_property')
    else:
        u_form = userUpdateForm(instance=request.user)
        p_form = profileUpdateForm(instance=request.user.profile)

    context= {
        'u_form':u_form,
        'p_form':p_form,
        
    }
    return render(request,'profile/profile.html',context)

def Demande(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('e-mail')
        phone = request.POST.get('phone')
        realtor = request.user.profile
        demande = Dem(profile=realtor, name=name, email=email, phone_number=phone)
        demande.save()
        realtor_id = realtor.id
        Pro.objects.filter(id=realtor_id).update(is_mvp=True)
        
        message = 'Votre demande de compte enseignant a été acceptée! Vous pouvez maintenant retourner sur Essikarea et télécharger des cours et des conférences, bon travail!'
        send_mail(
            'Essikarea, la demande a été acceptée.',
            message,
            'yvindjhonnelmahoukou@gmail.com',
            [email],
            fail_silently=False,
        )
        send_mail(
            'Essikarea',
            'Quelqu\'un a demandé un compte enseignant. Moi info: ' + name + ' , ' + email + ' , ' + phone + ' , ' + str(realtor) + '.',
            'yvindjhonnelmahoukou@gmail.com',
            ['yvindjhonnelmahoukou@gmail.com'],
            fail_silently=False,
        )
        messages.info(request, 'La demande a été envoyée avec succès, vous serez averti par email.')
        return redirect('listings:add_property')


def show_div(request):
    prop_hidden = request.Get.get('prop_hidden')
    
    data = {
        'prop_hidden':prop_hidden
    }
    return JsonResponse(data)

realtors/templates/realtors/realtor_detail.html
{% extends 'base.html'  %}
{% block title %} | Browse Properties {% endblock %}  
{% load humanize  %}

{% block content  %}

<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">Bienvenu sur le profil de {{ realtor.name}} </h1>
        <p class="lead">Vous trouverez tout sur cet agent ici.</p>
      </div>
    </div>
  </div>
</section>


<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href=" {% url 'index'  %} ">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Browse Listings</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">
        {% if realtor  %}

    

        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            {% if realtor.photo  %}
            <img class="card-img-top" src=" {{realtor.photo.url}}  " alt="photo">
            {% endif %}
            <div class="card-img-overlay">
              <h2>
                <span class="badge badge-secondary text-white"> {{realtor.user.username }}   </span>
              </h2>
            </div>
            <div class="card-body">
              <div class="listing-heading text-center">
                <h4 class="text-primary"> Description : {{realtor.description}}    </h4>
                <h4 class="text-primary">Date de recrutement : {{realtor.hire_date}}    </h4>
                {% if realtor.website_url %} :
                <h4 class="text-primary"> Website : {{realtor.website_url}}    </h4>
                {% endif %}
                {% if realtor.facebook_url %} :
                  <h4 class="text-primary"> Facebook : {{realtor.facebook_url}}    </h4>
                {% endif %}
                {% if realtor.instagram_url %} :
                  <h4 class="text-primary">Instagram : {{realtor.instagram_url}}    </h4>
                  {% endif %}
                  {% if realtor.twitter_url %} :
                  <h4 class="text-primary">Twitter : {{realtor.twitter_url}}    </h4>
                  {% endif %}
                  {% if realtor.linkedin_url %} :
                  <h4 class="text-primary">Linked_in : {{realtor.linkedin_url}}    </h4>
                  {% endif %}
               
               
             
              </div>
              <hr>

        {% else %}
          <div class="col-md-12">
            <h1>Aucun bien immobilier disponible</h1>
          </div>
        {% endif   %}

      </div>

      
        </div>
      </div>
    </div>
    </div>
  </section>


{% endblock  %}

realtors/templates/realtors/realtor_search.html
{% extends 'base.html'  %}

{% block title %} | Search Results {% endblock %}  

{% load humanize %}
{% block content  %}
<section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <form action="{% url 'realtors:realtor_search' %}">
            <!-- Form Row 1 -->
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">Mots clé</label>
                <input type="text" name="keywords" class="form-control" placeholder="Keyword (npm,description...)" 
                value="{{values.keywords}}"
                >
              </div>

             
              </div>
            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'listings:listings' %}">Browse Listings</a>
          </li>
          <li class="breadcrumb-item active"> Search Results</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <!-- Listings -->
  <section id="listings" class="py-5">
    <div class="container">
      <!-- <h3 class="text-center mb-3">Latest Listings</h3> -->
      <div class="row">

        {% if realtor_search %}

        {% for realtor in realtor_search  %}

        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img class="card-img-top" src="{{realtor.photo.url}}" alt="">
            <div class="card-img-overlay">
              <h2>
                <span class="badge badge-secondary text-white">{{realtor.name }}</span>
              </h2>
            </div>
           
              <hr>
              <a href=" {% url 'realtors:realtors_detail' realtor.id  %}  " class="btn btn-primary btn-block">More Info</a>
            </div>
          </div>
        </div>


        {% endfor %}

        {% else  %}
        <div class="col-md-12">
          <p>Aucun agent trouvé.</p>
        </div>

        {% endif %}

        
      </div>
    </div>
  </section>


{% endblock  %}

realtors/templates/realtors/realtor_sign_up.html
{% extends 'base.html'  %}

{% block title %} | Realtor Registration {% endblock %}  

{% block content  %}

<section id="register" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              {% if request.user.is_authenticated %}

<!-- signup section -->
{% if request.user.profile.is_mvp == True %}
  <h1 class="text-center">Votre compte dispose du droit d'agent immobilier</h1><br>
  <p class="text-center">
    En ayant un compte agent, vous avez déjà un accès complet à cette plateforme. Vous pouvez : </p>

  <div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
    <div class="col-md-4 text-center">
      <h3 class="p-4">Vous pouvez ajouter un bien immobilier</h3> 
      <a href="{% url 'listings:add_property' %}" class="btn btn-outline-primary m-4">Ajouter une propriété</a>
    </div>
    <div class="col-md-4 text-center">
      <h3 class="p-4">Gerez vos bien immobilier</h3> 
      <a href="{% url 'listings:add_property' %}" class="btn btn-outline-primary m-4">Voir vos biens</a>
    </div>
    
  </div>
  {% else %}

    
       
            <input type="text" placeholder="Email" name="e-mail">
            <input type="text" placeholder="Numéro de téléphone" name="phone">
            <button class="site-btn">
              Soumettre la demande</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endif %}
<!-- signup section end -->
{% else %}
{% endif %}
              <h4>
                <i class="fas fa-user-plus"></i> Enreigistrez vous en tant qu'agent</h4>
                <p>Pour vous inscrire en tant que professeur sur la plate-forme, vous devez remplir les champs suivants et vous aurez alors un accès complet pour télécharger des cours et des vidéos.</p>
            </div>
            <div class="card-body">

              {% include 'partials/_alert.html' %}

              <form action="/demande/" method="post" class="signup-form">
                    {% csrf_token  %}
                    <!-- Secure Data -->
                  <div class="form-group">
                  <label for="first_name"> Nom</label>
                  <input type="text" name="first_name" class="form-control" required>
                </div>
                
                <div class="form-group">
                  <label for="email">Email</label>
                  <input type="email" name="email" class="form-control" required>
                </div>
              
                <div class="form-group">
                  <label for="phone">Numéro de téléphone</label>
                  <input type="text" name="phone" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="photo">photo</label>
                  <input type="image" name="photo" class="form-control" required>
                </div>
               
                <input type="submit" value="Register" class="btn btn-secondary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock  %}



    

realtors/templates/realtors/realtors.html
{% extends 'base.html'  %}
{% block title %} | Browse Properties {% endblock %}  


{% block content  %}

<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">Voici la liste de nos Agents immobiliers</h1>
          <p class="lead">Vous pouvez rechercher un agent précis par son nom.</p>
      
        </div>
      </div>
    </div>
</section>


<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href=" {% url 'index'  %} ">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Realtors</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  
  <section id="listings" class="py-4">
   
    <div class="container">
     
      <div class="row">

        {% if realtors  %}

        {% for realtor in realtors   %}

        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img class="card-img-top" src=" {{realtor.photo.url}}  " alt="">
            <div class="card-img-overlay">
              <h2>
                <span class="badge badge-secondary text-white"> {{realtor.user.username  }}   </span>
              </h2>
            </div>
           
              <hr>
              <a href=" {% url 'realtors:realtors_detail' realtor.id  %} " class="btn btn-primary btn-block">More Info</a>
            </div>
          </div>
          {% endfor   %}
          
        <div class="col-md-6 col-lg-4 mb-4 text-right">
        
              <h2>
                <a href="{% url 'realtors:profile'  %} "><button class="btn btn-primary ">Devenir Agent immobilier</button></a>
              </h2>
            
            </div>
          </div>
        </div>



        


        {% else %}
          <div class="col-md-12">
            <h1>Aucun agent immobilier disponible</h1>
          </div>
        {% endif   %}

      </div>

      <div class="row">
        <div class="col-md-12">
          {% if realtors.has_other_pages %}
          <ul class="pagination">
            {% if realtors.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{realtors.previous_page_number}} ">&laquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link">&laquo;</a>
            </li>
            {% endif  %}
            {% for i in realtors.paginator.page_range  %}

            {% if realtors.number == i  %}
            <li class="page-item active">
              <a class="page-link" > {{i}} </a>
            </li>

            {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{i}}"> {{i}} </a>
            </li>
            {% endif  %}
            {% endfor %}
            {% if realtors.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{realtors.next_page_number}} ">&raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link">&raquo;</a>
            </li>
            {% endif  %}
          </ul>
          {% endif %}
        </div>
      </div>

    </div>
   
  </section>


{% endblock  %}